apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: fitness-tracker-app
  template:
    metadata:
      labels:
        app: fitness-tracker-app
    spec:
      containers:
        - name: fitness-tracker-app
          image: {{ .Values.app.image }}:{{ .Values.app.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: {{ .Values.app.mongodbUri }}
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: {{ .Values.app.nodeEnv }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE
              value: "fitness-tracker-app"
            - name: DD_ENV
              value: {{ .Values.app.nodeEnv }}
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
spec:
  selector:
    app: fitness-tracker-app
  ports:
    - port: 80
      targetPort: 5000
  type: {{ .Values.app.serviceType }}
